
# To kick the tires of the coordinates returned by gmaps, we want to also geocode using
# Open Street Maps' (osm) API, 'nominatim'

# https://towardsdatascience.com/breaking-down-geocoding-in-r-a-complete-guide-1d0f8acd0d4b

# load packages -----------------------------------------------------------

library(tidyverse)
library(here)
library(tmaptools)

# read in data ------------------------------------------------------------

accidents_with_coords <- read_csv(here("proc/addresses-with-gmaps-coordinates.csv"),
                                  col_types = cols(
                                    .default = col_character(),
                                    crash_report_id = col_double(),
                                    crash_date = col_date(format = ""),
                                    crash_time = col_time(format = ""),
                                    numberof_vehicles = col_double(),
                                    person_count = col_double(),
                                    injury_count = col_double(),
                                    has_st_number = col_logical(),
                                    row_number = col_double(),
                                    autocompletion_found = col_logical(),
                                    lon = col_double(),
                                    lat = col_double(),
                                    north = col_double(),
                                    south = col_double(),
                                    east = col_double(),
                                    west = col_double()))

# geocode with nominatim --------------------------------------------------

# reformat address in a nominatim friendly way
addresses_for_nominatim_geocoder <- accidents_with_coords %>% 
  mutate(address_for_geocoder_nominatim = str_replace(address_original, " and ", " & ")) %>% 
  pull(address_for_geocoder_nominatim) 

geo_results <- geocode_OSM(q = addresses_for_nominatim_geocoder,
                           # projection = "EPSG 4326", # WGS84 is the default which should match gmaps crs
                           return.first.only = T,
                           keep.unfound = T,
                           as.data.frame = T)

geo_results_selected <- geo_results %>% 
  select(nominatim_lat = lat, 
         nominatim_lon = lon)

combined_df <- bind_cols(accidents_with_coords, geo_results_selected)

# cleanup -----------------------------------------------------------------

# add a "gmaps" prefix to columns generated by a gmaps api

final <- combined_df %>% 
  rename_with(.fn = ~paste0("gmaps_", .x), 
              .cols = all_of(c("lon", "lat", "type", "loctype", "autocompletion_found",
                               "address_autocompleted", "address_returned_by_geocoder"))) %>% 
  rename_with(~paste0("raw_", .x),
              all_of(c("street_or_highway", "nearest_intersection", "location"))) %>% 
  rename("manner_of_impact" = "mannerof_impact") %>% 
  select(-c(south, north, east, west)) %>% 
  mutate(bicycle = case_when(bicycle == "X" ~ T, T ~ F),
         scooter = case_when(scooter == "X" ~ T, T ~ F),
         wheel_chair = case_when(wheel_chair == "X" ~ T, T ~ F))

# write out ---------------------------------------------------------------

accidents_with_coords %>% 
  write_csv(here::here("proc/addresses-with-gmaps-and-osm-coordinates.csv"))

